name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master   # o "main", depende de tu rama

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./src   # 👈 carpeta donde tienes index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
